apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: $LOKI_URL
    isDefault: true
    editable: true
    jsonData:
      maxLines: 1000
      timeout: 60s
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "1"

  - name: Prometheus
    type: prometheus
    access: proxy
    url: $PROMETHEUS_URL
    isDefault: false
    editable: true
    jsonData:
      timeInterval: "15s"
